(function () {

/* Imports */
var Meteor = Package.meteor.Meteor;
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;
var ECMAScript = Package.ecmascript.ECMAScript;
var RocketChat = Package['rocketchat:lib'].RocketChat;
var meteorInstall = Package.modules.meteorInstall;
var meteorBabelHelpers = Package['babel-runtime'].meteorBabelHelpers;
var Promise = Package.promise.Promise;
var TAPi18next = Package['tap:i18n'].TAPi18next;
var TAPi18n = Package['tap:i18n'].TAPi18n;

/* Package-scope variables */
var str, message;

var require = meteorInstall({"node_modules":{"meteor":{"rocketchat:katex":{"settings.js":function(){

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                    //
// packages/rocketchat_katex/settings.js                                                                              //
//                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                      //
Meteor.startup(function () {
  const enableQuery = {
    _id: 'Katex_Enabled',
    value: true
  };
  RocketChat.settings.add('Katex_Enabled', true, {
    type: 'boolean',
    group: 'Message',
    section: 'Katex',
    'public': true,
    i18n: 'Katex_Enabled_Description'
  });
  RocketChat.settings.add('Katex_Parenthesis_Syntax', true, {
    type: 'boolean',
    group: 'Message',
    section: 'Katex',
    'public': true,
    enableQuery,
    i18nDescription: 'Katex_Parenthesis_Syntax_Description'
  });
  return RocketChat.settings.add('Katex_Dollar_Syntax', false, {
    type: 'boolean',
    group: 'Message',
    section: 'Katex',
    'public': true,
    enableQuery,
    i18nDescription: 'Katex_Dollar_Syntax_Description'
  });
}); // ---
// generated by coffee-script 1.9.2
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"katex.js":function(require,exports,module){

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                    //
// packages/rocketchat_katex/katex.js                                                                                 //
//                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                      //
let _;

module.watch(require("underscore"), {
  default(v) {
    _ = v;
  }

}, 0);
let s;
module.watch(require("underscore.string"), {
  default(v) {
    s = v;
  }

}, 1);
let katex;
module.watch(require("katex"), {
  default(v) {
    katex = v;
  }

}, 2);

class Boundary {
  constructor() {}

  length() {
    return this.end - this.start;
  }

  extract(str) {
    return str.substr(this.start, this.length());
  }

}

class Katex {
  constructor() {
    this.delimiters_map = [{
      opener: '\\[',
      closer: '\\]',
      displayMode: true,
      enabled: () => {
        return this.parenthesis_syntax_enabled();
      }
    }, {
      opener: '\\(',
      closer: '\\)',
      displayMode: false,
      enabled: () => {
        return this.parenthesis_syntax_enabled();
      }
    }, {
      opener: '$$',
      closer: '$$',
      displayMode: true,
      enabled: () => {
        return this.dollar_syntax_enabled();
      }
    }, {
      opener: '$',
      closer: '$',
      displayMode: false,
      enabled: () => {
        return this.dollar_syntax_enabled();
      }
    }];
  } // Searches for the first opening delimiter in the string from a given position


  find_opening_delimiter(str, start) {
    // Search the string for each opening delimiter
    const matches = (() => {
      const map = this.delimiters_map;
      const results = [];
      map.forEach(op => {
        if (op.enabled()) {
          results.push({
            options: op,
            pos: str.indexOf(op.opener, start)
          });
        }
      });
      return results;
    })();

    const positions = (() => {
      const results = [];
      matches.forEach(pos => {
        if (pos.pos >= 0) {
          results.push(pos.pos);
        }
      });
      return results;
    })(); // No opening delimiters were found


    if (positions.length === 0) {
      return null;
    } //Take the first delimiter found


    const pos = Math.min.apply(Math, positions);

    const match_index = (() => {
      const results = [];
      matches.forEach(m => {
        results.push(m.pos);
      });
      return results;
    })().indexOf(pos);

    const match = matches[match_index];
    return match;
  } // Returns the outer and inner boundaries of the latex block starting
  // at the given opening delimiter


  get_latex_boundaries(str, opening_delimiter_match) {
    const inner = new Boundary();
    const outer = new Boundary(); // The closing delimiter matching to the opening one

    const closer = opening_delimiter_match.options.closer;
    outer.start = opening_delimiter_match.pos;
    inner.start = opening_delimiter_match.pos + closer.length; // Search for a closer delimiter after the opening one

    const closer_index = str.substr(inner.start).indexOf(closer);

    if (closer_index < 0) {
      return null;
    }

    inner.end = inner.start + closer_index;
    outer.end = inner.end + closer.length;
    return {
      outer,
      inner
    };
  } // Searches for the first latex block in the given string


  find_latex(str) {
    let start = 0;
    let opening_delimiter_match;

    while ((opening_delimiter_match = this.find_opening_delimiter(str, start++)) != null) {
      const match = this.get_latex_boundaries(str, opening_delimiter_match);

      if (match && match.inner.extract(str).trim().length) {
        match.options = opening_delimiter_match.options;
        return match;
      }
    }

    return null;
  } // Breaks a message to what comes before, after and to the content of a
  // matched latex block


  extract_latex(str, match) {
    const before = str.substr(0, match.outer.start);
    const after = str.substr(match.outer.end);
    let latex = match.inner.extract(str);
    latex = s.unescapeHTML(latex);
    return {
      before,
      latex,
      after
    };
  } // Takes a latex math string and the desired display mode and renders it
  // to HTML using the KaTeX library


  render_latex(latex, displayMode) {
    let rendered;

    try {
      rendered = katex.renderToString(latex, {
        displayMode
      });
    } catch (error) {
      const e = error;
      const display_mode = displayMode ? 'block' : 'inline';
      rendered = `<div class="katex-error katex-${display_mode}-error">`;
      rendered += `${s.escapeHTML(e.message)}`;
      rendered += '</div>';
    }

    return rendered;
  } // Takes a string and renders all latex blocks inside it


  render(str, render_func) {
    let result = '';

    while (this.find_latex(str) != null) {
      // Find the first latex block in the string
      const match = this.find_latex(str);
      const parts = this.extract_latex(str, match); // Add to the reuslt what comes before the latex block as well as
      // the rendered latex content

      const rendered = render_func(parts.latex, match.options.displayMode);
      result += parts.before + rendered; // Set what comes after the latex block to be examined next

      str = parts.after;
    }

    return result += str;
  } // Takes a rocketchat message and renders latex in its content


  render_message(message) {
    //Render only if enabled in admin panel
    let render_func;

    if (this.katex_enabled()) {
      let msg = message;

      if (!_.isString(message)) {
        if (s.trim(message.html)) {
          msg = message.html;
        } else {
          return message;
        }
      }

      if (_.isString(message)) {
        render_func = (latex, displayMode) => {
          return this.render_latex(latex, displayMode);
        };
      } else {
        if (message.tokens == null) {
          message.tokens = [];
        }

        render_func = (latex, displayMode) => {
          const token = `=!=${Random.id()}=!=`;
          message.tokens.push({
            token,
            text: this.render_latex(latex, displayMode)
          });
          return token;
        };
      }

      msg = this.render(msg, render_func);

      if (!_.isString(message)) {
        message.html = msg;
      } else {
        message = msg;
      }
    }

    return message;
  }

  katex_enabled() {
    return RocketChat.settings.get('Katex_Enabled');
  }

  dollar_syntax_enabled() {
    return RocketChat.settings.get('Katex_Dollar_Syntax');
  }

  parenthesis_syntax_enabled() {
    return RocketChat.settings.get('Katex_Parenthesis_Syntax');
  }

}

RocketChat.katex = new Katex();
const cb = RocketChat.katex.render_message.bind(RocketChat.katex);
RocketChat.callbacks.add('renderMessage', cb, RocketChat.callbacks.priority.HIGH - 1, 'katex');

if (Meteor.isClient) {
  Blaze.registerHelper('RocketChatKatex', function (text) {
    return RocketChat.katex.render_message(text);
  });
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"node_modules":{"katex":{"package.json":function(require,exports){

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                    //
// node_modules/meteor/rocketchat_katex/node_modules/katex/package.json                                               //
//                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                      //
exports.name = "katex";
exports.version = "0.7.1";
exports.main = "katex.js";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"katex.js":function(require,exports,module){

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                    //
// node_modules/meteor/rocketchat_katex/node_modules/katex/katex.js                                                   //
//                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                      //
/* eslint no-console:0 */
/**
 * This is the main entry point for KaTeX. Here, we expose functions for
 * rendering expressions either to DOM nodes or to markup strings.
 *
 * We also expose the ParseError class to check if errors thrown from KaTeX are
 * errors in the expression, or errors in javascript handling.
 */

var ParseError = require("./src/ParseError");
var Settings = require("./src/Settings");

var buildTree = require("./src/buildTree");
var parseTree = require("./src/parseTree");
var utils = require("./src/utils");

/**
 * Parse and build an expression, and place that expression in the DOM node
 * given.
 */
var render = function(expression, baseNode, options) {
    utils.clearNode(baseNode);

    var settings = new Settings(options);

    var tree = parseTree(expression, settings);
    var node = buildTree(tree, expression, settings).toNode();

    baseNode.appendChild(node);
};

// KaTeX's styles don't work properly in quirks mode. Print out an error, and
// disable rendering.
if (typeof document !== "undefined") {
    if (document.compatMode !== "CSS1Compat") {
        typeof console !== "undefined" && console.warn(
            "Warning: KaTeX doesn't work in quirks mode. Make sure your " +
                "website has a suitable doctype.");

        render = function() {
            throw new ParseError("KaTeX doesn't work in quirks mode.");
        };
    }
}

/**
 * Parse and build an expression, and return the markup for that.
 */
var renderToString = function(expression, options) {
    var settings = new Settings(options);

    var tree = parseTree(expression, settings);
    return buildTree(tree, expression, settings).toMarkup();
};

/**
 * Parse an expression and return the parse tree.
 */
var generateParseTree = function(expression, options) {
    var settings = new Settings(options);
    return parseTree(expression, settings);
};

module.exports = {
    render: render,
    renderToString: renderToString,
    /**
     * NOTE: This method is not currently recommended for public use.
     * The internal tree representation is unstable and is very likely
     * to change. Use at your own risk.
     */
    __parse: generateParseTree,
    ParseError: ParseError
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}}}}}}},{
  "extensions": [
    ".js",
    ".json"
  ]
});
require("/node_modules/meteor/rocketchat:katex/settings.js");
require("/node_modules/meteor/rocketchat:katex/katex.js");

/* Exports */
Package._define("rocketchat:katex");

})();

//# sourceURL=meteor://💻app/packages/rocketchat_katex.js
//# sourceMappingURL=data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm1ldGVvcjovL/CfkrthcHAvcGFja2FnZXMvcm9ja2V0Y2hhdDprYXRleC9zZXR0aW5ncy5qcyIsIm1ldGVvcjovL/CfkrthcHAvcGFja2FnZXMvcm9ja2V0Y2hhdDprYXRleC9rYXRleC5qcyJdLCJuYW1lcyI6WyJNZXRlb3IiLCJzdGFydHVwIiwiZW5hYmxlUXVlcnkiLCJfaWQiLCJ2YWx1ZSIsIlJvY2tldENoYXQiLCJzZXR0aW5ncyIsImFkZCIsInR5cGUiLCJncm91cCIsInNlY3Rpb24iLCJpMThuIiwiaTE4bkRlc2NyaXB0aW9uIiwiXyIsIm1vZHVsZSIsIndhdGNoIiwicmVxdWlyZSIsImRlZmF1bHQiLCJ2IiwicyIsImthdGV4IiwiQm91bmRhcnkiLCJjb25zdHJ1Y3RvciIsImxlbmd0aCIsImVuZCIsInN0YXJ0IiwiZXh0cmFjdCIsInN0ciIsInN1YnN0ciIsIkthdGV4IiwiZGVsaW1pdGVyc19tYXAiLCJvcGVuZXIiLCJjbG9zZXIiLCJkaXNwbGF5TW9kZSIsImVuYWJsZWQiLCJwYXJlbnRoZXNpc19zeW50YXhfZW5hYmxlZCIsImRvbGxhcl9zeW50YXhfZW5hYmxlZCIsImZpbmRfb3BlbmluZ19kZWxpbWl0ZXIiLCJtYXRjaGVzIiwibWFwIiwicmVzdWx0cyIsImZvckVhY2giLCJvcCIsInB1c2giLCJvcHRpb25zIiwicG9zIiwiaW5kZXhPZiIsInBvc2l0aW9ucyIsIk1hdGgiLCJtaW4iLCJhcHBseSIsIm1hdGNoX2luZGV4IiwibSIsIm1hdGNoIiwiZ2V0X2xhdGV4X2JvdW5kYXJpZXMiLCJvcGVuaW5nX2RlbGltaXRlcl9tYXRjaCIsImlubmVyIiwib3V0ZXIiLCJjbG9zZXJfaW5kZXgiLCJmaW5kX2xhdGV4IiwidHJpbSIsImV4dHJhY3RfbGF0ZXgiLCJiZWZvcmUiLCJhZnRlciIsImxhdGV4IiwidW5lc2NhcGVIVE1MIiwicmVuZGVyX2xhdGV4IiwicmVuZGVyZWQiLCJyZW5kZXJUb1N0cmluZyIsImVycm9yIiwiZSIsImRpc3BsYXlfbW9kZSIsImVzY2FwZUhUTUwiLCJtZXNzYWdlIiwicmVuZGVyIiwicmVuZGVyX2Z1bmMiLCJyZXN1bHQiLCJwYXJ0cyIsInJlbmRlcl9tZXNzYWdlIiwia2F0ZXhfZW5hYmxlZCIsIm1zZyIsImlzU3RyaW5nIiwiaHRtbCIsInRva2VucyIsInRva2VuIiwiUmFuZG9tIiwiaWQiLCJ0ZXh0IiwiZ2V0IiwiY2IiLCJiaW5kIiwiY2FsbGJhY2tzIiwicHJpb3JpdHkiLCJISUdIIiwiaXNDbGllbnQiLCJCbGF6ZSIsInJlZ2lzdGVySGVscGVyIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQUFBLE9BQU9DLE9BQVAsQ0FBZSxZQUFXO0FBQ3pCLFFBQU1DLGNBQWM7QUFDbkJDLFNBQUssZUFEYztBQUVuQkMsV0FBTztBQUZZLEdBQXBCO0FBSUFDLGFBQVdDLFFBQVgsQ0FBb0JDLEdBQXBCLENBQXdCLGVBQXhCLEVBQXlDLElBQXpDLEVBQStDO0FBQzlDQyxVQUFNLFNBRHdDO0FBRTlDQyxXQUFPLFNBRnVDO0FBRzlDQyxhQUFTLE9BSHFDO0FBSTlDLGNBQVUsSUFKb0M7QUFLOUNDLFVBQU07QUFMd0MsR0FBL0M7QUFPQU4sYUFBV0MsUUFBWCxDQUFvQkMsR0FBcEIsQ0FBd0IsMEJBQXhCLEVBQW9ELElBQXBELEVBQTBEO0FBQ3pEQyxVQUFNLFNBRG1EO0FBRXpEQyxXQUFPLFNBRmtEO0FBR3pEQyxhQUFTLE9BSGdEO0FBSXpELGNBQVUsSUFKK0M7QUFLekRSLGVBTHlEO0FBTXpEVSxxQkFBaUI7QUFOd0MsR0FBMUQ7QUFRQSxTQUFPUCxXQUFXQyxRQUFYLENBQW9CQyxHQUFwQixDQUF3QixxQkFBeEIsRUFBK0MsS0FBL0MsRUFBc0Q7QUFDNURDLFVBQU0sU0FEc0Q7QUFFNURDLFdBQU8sU0FGcUQ7QUFHNURDLGFBQVMsT0FIbUQ7QUFJNUQsY0FBVSxJQUprRDtBQUs1RFIsZUFMNEQ7QUFNNURVLHFCQUFpQjtBQU4yQyxHQUF0RCxDQUFQO0FBUUEsQ0E1QkQsRSxDQThCQTtBQUNBLG1DOzs7Ozs7Ozs7OztBQy9CQSxJQUFJQyxDQUFKOztBQUFNQyxPQUFPQyxLQUFQLENBQWFDLFFBQVEsWUFBUixDQUFiLEVBQW1DO0FBQUNDLFVBQVFDLENBQVIsRUFBVTtBQUFDTCxRQUFFSyxDQUFGO0FBQUk7O0FBQWhCLENBQW5DLEVBQXFELENBQXJEO0FBQXdELElBQUlDLENBQUo7QUFBTUwsT0FBT0MsS0FBUCxDQUFhQyxRQUFRLG1CQUFSLENBQWIsRUFBMEM7QUFBQ0MsVUFBUUMsQ0FBUixFQUFVO0FBQUNDLFFBQUVELENBQUY7QUFBSTs7QUFBaEIsQ0FBMUMsRUFBNEQsQ0FBNUQ7QUFBK0QsSUFBSUUsS0FBSjtBQUFVTixPQUFPQyxLQUFQLENBQWFDLFFBQVEsT0FBUixDQUFiLEVBQThCO0FBQUNDLFVBQVFDLENBQVIsRUFBVTtBQUFDRSxZQUFNRixDQUFOO0FBQVE7O0FBQXBCLENBQTlCLEVBQW9ELENBQXBEOztBQVM3SSxNQUFNRyxRQUFOLENBQWU7QUFDZEMsZ0JBQWMsQ0FBRTs7QUFFaEJDLFdBQVM7QUFDUixXQUFPLEtBQUtDLEdBQUwsR0FBVyxLQUFLQyxLQUF2QjtBQUNBOztBQUVEQyxVQUFRQyxHQUFSLEVBQWE7QUFDWixXQUFPQSxJQUFJQyxNQUFKLENBQVcsS0FBS0gsS0FBaEIsRUFBdUIsS0FBS0YsTUFBTCxFQUF2QixDQUFQO0FBQ0E7O0FBVGE7O0FBYWYsTUFBTU0sS0FBTixDQUFZO0FBQ1hQLGdCQUFjO0FBQ2IsU0FBS1EsY0FBTCxHQUFzQixDQUNyQjtBQUNDQyxjQUFRLEtBRFQ7QUFFQ0MsY0FBUSxLQUZUO0FBR0NDLG1CQUFhLElBSGQ7QUFJQ0MsZUFBUyxNQUFNO0FBQ2QsZUFBTyxLQUFLQywwQkFBTCxFQUFQO0FBQ0E7QUFORixLQURxQixFQVFsQjtBQUNGSixjQUFRLEtBRE47QUFFRkMsY0FBUSxLQUZOO0FBR0ZDLG1CQUFhLEtBSFg7QUFJRkMsZUFBUyxNQUFNO0FBQ2QsZUFBTyxLQUFLQywwQkFBTCxFQUFQO0FBQ0E7QUFOQyxLQVJrQixFQWVsQjtBQUNGSixjQUFRLElBRE47QUFFRkMsY0FBUSxJQUZOO0FBR0ZDLG1CQUFhLElBSFg7QUFJRkMsZUFBUyxNQUFNO0FBQ2QsZUFBTyxLQUFLRSxxQkFBTCxFQUFQO0FBQ0E7QUFOQyxLQWZrQixFQXNCbEI7QUFDRkwsY0FBUSxHQUROO0FBRUZDLGNBQVEsR0FGTjtBQUdGQyxtQkFBYSxLQUhYO0FBSUZDLGVBQVMsTUFBTTtBQUNkLGVBQU8sS0FBS0UscUJBQUwsRUFBUDtBQUNBO0FBTkMsS0F0QmtCLENBQXRCO0FBK0JBLEdBakNVLENBa0NYOzs7QUFFQUMseUJBQXVCVixHQUF2QixFQUE0QkYsS0FBNUIsRUFBbUM7QUFBRTtBQUNwQyxVQUFNYSxVQUFVLENBQUMsTUFBTTtBQUN0QixZQUFNQyxNQUFNLEtBQUtULGNBQWpCO0FBQ0EsWUFBTVUsVUFBVSxFQUFoQjtBQUVBRCxVQUFJRSxPQUFKLENBQWFDLEVBQUQsSUFBUTtBQUNuQixZQUFJQSxHQUFHUixPQUFILEVBQUosRUFBa0I7QUFDakJNLGtCQUFRRyxJQUFSLENBQWE7QUFDWkMscUJBQVNGLEVBREc7QUFFWkcsaUJBQUtsQixJQUFJbUIsT0FBSixDQUFZSixHQUFHWCxNQUFmLEVBQXVCTixLQUF2QjtBQUZPLFdBQWI7QUFJQTtBQUNELE9BUEQ7QUFRQSxhQUFPZSxPQUFQO0FBQ0EsS0FiZSxHQUFoQjs7QUFlQSxVQUFNTyxZQUFZLENBQUMsTUFBTTtBQUN4QixZQUFNUCxVQUFVLEVBQWhCO0FBQ0FGLGNBQVFHLE9BQVIsQ0FBaUJJLEdBQUQsSUFBUztBQUN4QixZQUFJQSxJQUFJQSxHQUFKLElBQVcsQ0FBZixFQUFrQjtBQUNqQkwsa0JBQVFHLElBQVIsQ0FBYUUsSUFBSUEsR0FBakI7QUFDQTtBQUNELE9BSkQ7QUFLQSxhQUFPTCxPQUFQO0FBQ0EsS0FSaUIsR0FBbEIsQ0FoQmtDLENBMEJsQzs7O0FBQ0EsUUFBSU8sVUFBVXhCLE1BQVYsS0FBcUIsQ0FBekIsRUFBNEI7QUFDM0IsYUFBTyxJQUFQO0FBQ0EsS0E3QmlDLENBK0JsQzs7O0FBQ0EsVUFBTXNCLE1BQU1HLEtBQUtDLEdBQUwsQ0FBU0MsS0FBVCxDQUFlRixJQUFmLEVBQXFCRCxTQUFyQixDQUFaOztBQUVBLFVBQU1JLGNBQWMsQ0FBQyxNQUFLO0FBQ3pCLFlBQU1YLFVBQVUsRUFBaEI7QUFDQUYsY0FBUUcsT0FBUixDQUFpQlcsQ0FBRCxJQUFPO0FBQ3RCWixnQkFBUUcsSUFBUixDQUFhUyxFQUFFUCxHQUFmO0FBQ0EsT0FGRDtBQUdBLGFBQU9MLE9BQVA7QUFDQSxLQU5tQixJQU1mTSxPQU5lLENBTVBELEdBTk8sQ0FBcEI7O0FBUUEsVUFBTVEsUUFBUWYsUUFBUWEsV0FBUixDQUFkO0FBQ0EsV0FBT0UsS0FBUDtBQUNBLEdBaEZVLENBa0ZYO0FBQ0E7OztBQUNBQyx1QkFBcUIzQixHQUFyQixFQUEwQjRCLHVCQUExQixFQUFtRDtBQUNsRCxVQUFNQyxRQUFRLElBQUluQyxRQUFKLEVBQWQ7QUFDQSxVQUFNb0MsUUFBUSxJQUFJcEMsUUFBSixFQUFkLENBRmtELENBSWxEOztBQUNBLFVBQU1XLFNBQVN1Qix3QkFBd0JYLE9BQXhCLENBQWdDWixNQUEvQztBQUNBeUIsVUFBTWhDLEtBQU4sR0FBYzhCLHdCQUF3QlYsR0FBdEM7QUFDQVcsVUFBTS9CLEtBQU4sR0FBYzhCLHdCQUF3QlYsR0FBeEIsR0FBOEJiLE9BQU9ULE1BQW5ELENBUGtELENBU2xEOztBQUNBLFVBQU1tQyxlQUFlL0IsSUFBSUMsTUFBSixDQUFXNEIsTUFBTS9CLEtBQWpCLEVBQXdCcUIsT0FBeEIsQ0FBZ0NkLE1BQWhDLENBQXJCOztBQUNBLFFBQUkwQixlQUFlLENBQW5CLEVBQXNCO0FBQ3JCLGFBQU8sSUFBUDtBQUNBOztBQUNERixVQUFNaEMsR0FBTixHQUFZZ0MsTUFBTS9CLEtBQU4sR0FBY2lDLFlBQTFCO0FBQ0FELFVBQU1qQyxHQUFOLEdBQVlnQyxNQUFNaEMsR0FBTixHQUFZUSxPQUFPVCxNQUEvQjtBQUNBLFdBQU87QUFDTmtDLFdBRE07QUFFTkQ7QUFGTSxLQUFQO0FBSUEsR0F4R1UsQ0EwR1g7OztBQUNBRyxhQUFXaEMsR0FBWCxFQUFnQjtBQUNmLFFBQUlGLFFBQVEsQ0FBWjtBQUNBLFFBQUk4Qix1QkFBSjs7QUFFQSxXQUFPLENBQUNBLDBCQUEwQixLQUFLbEIsc0JBQUwsQ0FBNEJWLEdBQTVCLEVBQWlDRixPQUFqQyxDQUEzQixLQUF5RSxJQUFoRixFQUFzRjtBQUNyRixZQUFNNEIsUUFBUSxLQUFLQyxvQkFBTCxDQUEwQjNCLEdBQTFCLEVBQStCNEIsdUJBQS9CLENBQWQ7O0FBQ0EsVUFBSUYsU0FBU0EsTUFBTUcsS0FBTixDQUFZOUIsT0FBWixDQUFvQkMsR0FBcEIsRUFBeUJpQyxJQUF6QixHQUFnQ3JDLE1BQTdDLEVBQXFEO0FBQ3BEOEIsY0FBTVQsT0FBTixHQUFnQlcsd0JBQXdCWCxPQUF4QztBQUNBLGVBQU9TLEtBQVA7QUFDQTtBQUNEOztBQUNELFdBQU8sSUFBUDtBQUNBLEdBdkhVLENBeUhYO0FBQ0E7OztBQUNBUSxnQkFBY2xDLEdBQWQsRUFBbUIwQixLQUFuQixFQUEwQjtBQUN6QixVQUFNUyxTQUFTbkMsSUFBSUMsTUFBSixDQUFXLENBQVgsRUFBY3lCLE1BQU1JLEtBQU4sQ0FBWWhDLEtBQTFCLENBQWY7QUFDQSxVQUFNc0MsUUFBUXBDLElBQUlDLE1BQUosQ0FBV3lCLE1BQU1JLEtBQU4sQ0FBWWpDLEdBQXZCLENBQWQ7QUFDQSxRQUFJd0MsUUFBUVgsTUFBTUcsS0FBTixDQUFZOUIsT0FBWixDQUFvQkMsR0FBcEIsQ0FBWjtBQUNBcUMsWUFBUTdDLEVBQUU4QyxZQUFGLENBQWVELEtBQWYsQ0FBUjtBQUNBLFdBQU87QUFDTkYsWUFETTtBQUVORSxXQUZNO0FBR05EO0FBSE0sS0FBUDtBQUtBLEdBcklVLENBdUlYO0FBQ0E7OztBQUNBRyxlQUFhRixLQUFiLEVBQW9CL0IsV0FBcEIsRUFBaUM7QUFDaEMsUUFBSWtDLFFBQUo7O0FBQ0EsUUFBSTtBQUNIQSxpQkFBVy9DLE1BQU1nRCxjQUFOLENBQXFCSixLQUFyQixFQUE0QjtBQUN0Qy9CO0FBRHNDLE9BQTVCLENBQVg7QUFHQSxLQUpELENBSUUsT0FBT29DLEtBQVAsRUFBYztBQUNmLFlBQU1DLElBQUlELEtBQVY7QUFDQSxZQUFNRSxlQUFldEMsY0FBYyxPQUFkLEdBQXdCLFFBQTdDO0FBQ0FrQyxpQkFBWSxpQ0FBaUNJLFlBQWMsVUFBM0Q7QUFDQUosa0JBQWEsR0FBR2hELEVBQUVxRCxVQUFGLENBQWFGLEVBQUVHLE9BQWYsQ0FBeUIsRUFBekM7QUFDQU4sa0JBQVksUUFBWjtBQUNBOztBQUNELFdBQU9BLFFBQVA7QUFDQSxHQXZKVSxDQXlKWDs7O0FBQ0FPLFNBQU8vQyxHQUFQLEVBQVlnRCxXQUFaLEVBQXlCO0FBQ3hCLFFBQUlDLFNBQVMsRUFBYjs7QUFDQSxXQUFPLEtBQUtqQixVQUFMLENBQWdCaEMsR0FBaEIsS0FBd0IsSUFBL0IsRUFBcUM7QUFDcEM7QUFDQSxZQUFNMEIsUUFBUSxLQUFLTSxVQUFMLENBQWdCaEMsR0FBaEIsQ0FBZDtBQUNBLFlBQU1rRCxRQUFRLEtBQUtoQixhQUFMLENBQW1CbEMsR0FBbkIsRUFBd0IwQixLQUF4QixDQUFkLENBSG9DLENBS3BDO0FBQ0E7O0FBQ0EsWUFBTWMsV0FBV1EsWUFBWUUsTUFBTWIsS0FBbEIsRUFBeUJYLE1BQU1ULE9BQU4sQ0FBY1gsV0FBdkMsQ0FBakI7QUFDQTJDLGdCQUFVQyxNQUFNZixNQUFOLEdBQWVLLFFBQXpCLENBUm9DLENBU3BDOztBQUNBeEMsWUFBTWtELE1BQU1kLEtBQVo7QUFDQTs7QUFDRCxXQUFPYSxVQUFVakQsR0FBakI7QUFDQSxHQXpLVSxDQTJLWDs7O0FBQ0FtRCxpQkFBZUwsT0FBZixFQUF3QjtBQUN2QjtBQUNBLFFBQUlFLFdBQUo7O0FBQ0EsUUFBSSxLQUFLSSxhQUFMLEVBQUosRUFBMEI7QUFDekIsVUFBSUMsTUFBTVAsT0FBVjs7QUFDQSxVQUFJLENBQUM1RCxFQUFFb0UsUUFBRixDQUFXUixPQUFYLENBQUwsRUFBMEI7QUFDekIsWUFBSXRELEVBQUV5QyxJQUFGLENBQU9hLFFBQVFTLElBQWYsQ0FBSixFQUEwQjtBQUN6QkYsZ0JBQU1QLFFBQVFTLElBQWQ7QUFDQSxTQUZELE1BRU87QUFDTixpQkFBT1QsT0FBUDtBQUNBO0FBQ0Q7O0FBQ0QsVUFBSTVELEVBQUVvRSxRQUFGLENBQVdSLE9BQVgsQ0FBSixFQUF5QjtBQUN4QkUsc0JBQWMsQ0FBQ1gsS0FBRCxFQUFRL0IsV0FBUixLQUF3QjtBQUNyQyxpQkFBTyxLQUFLaUMsWUFBTCxDQUFrQkYsS0FBbEIsRUFBeUIvQixXQUF6QixDQUFQO0FBQ0EsU0FGRDtBQUdBLE9BSkQsTUFJTztBQUNOLFlBQUl3QyxRQUFRVSxNQUFSLElBQWtCLElBQXRCLEVBQTRCO0FBQzNCVixrQkFBUVUsTUFBUixHQUFpQixFQUFqQjtBQUNBOztBQUNEUixzQkFBYyxDQUFDWCxLQUFELEVBQVEvQixXQUFSLEtBQXdCO0FBQ3JDLGdCQUFNbUQsUUFBUyxNQUFNQyxPQUFPQyxFQUFQLEVBQWEsS0FBbEM7QUFDQWIsa0JBQVFVLE1BQVIsQ0FBZXhDLElBQWYsQ0FBb0I7QUFDbkJ5QyxpQkFEbUI7QUFFbkJHLGtCQUFNLEtBQUtyQixZQUFMLENBQWtCRixLQUFsQixFQUF5Qi9CLFdBQXpCO0FBRmEsV0FBcEI7QUFJQSxpQkFBT21ELEtBQVA7QUFDQSxTQVBEO0FBUUE7O0FBQ0RKLFlBQU0sS0FBS04sTUFBTCxDQUFZTSxHQUFaLEVBQWlCTCxXQUFqQixDQUFOOztBQUNBLFVBQUksQ0FBQzlELEVBQUVvRSxRQUFGLENBQVdSLE9BQVgsQ0FBTCxFQUEwQjtBQUN6QkEsZ0JBQVFTLElBQVIsR0FBZUYsR0FBZjtBQUNBLE9BRkQsTUFFTztBQUNOUCxrQkFBVU8sR0FBVjtBQUNBO0FBQ0Q7O0FBQ0QsV0FBT1AsT0FBUDtBQUNBOztBQUVETSxrQkFBZ0I7QUFDZixXQUFPMUUsV0FBV0MsUUFBWCxDQUFvQmtGLEdBQXBCLENBQXdCLGVBQXhCLENBQVA7QUFDQTs7QUFFRHBELDBCQUF3QjtBQUN2QixXQUFPL0IsV0FBV0MsUUFBWCxDQUFvQmtGLEdBQXBCLENBQXdCLHFCQUF4QixDQUFQO0FBQ0E7O0FBRURyRCwrQkFBNkI7QUFDNUIsV0FBTzlCLFdBQVdDLFFBQVgsQ0FBb0JrRixHQUFwQixDQUF3QiwwQkFBeEIsQ0FBUDtBQUNBOztBQTdOVTs7QUFpT1puRixXQUFXZSxLQUFYLEdBQW1CLElBQUlTLEtBQUosRUFBbkI7QUFFQSxNQUFNNEQsS0FBS3BGLFdBQVdlLEtBQVgsQ0FBaUIwRCxjQUFqQixDQUFnQ1ksSUFBaEMsQ0FBcUNyRixXQUFXZSxLQUFoRCxDQUFYO0FBRUFmLFdBQVdzRixTQUFYLENBQXFCcEYsR0FBckIsQ0FBeUIsZUFBekIsRUFBMENrRixFQUExQyxFQUE4Q3BGLFdBQVdzRixTQUFYLENBQXFCQyxRQUFyQixDQUE4QkMsSUFBOUIsR0FBcUMsQ0FBbkYsRUFBc0YsT0FBdEY7O0FBRUEsSUFBSTdGLE9BQU84RixRQUFYLEVBQXFCO0FBQ3BCQyxRQUFNQyxjQUFOLENBQXFCLGlCQUFyQixFQUF3QyxVQUFTVCxJQUFULEVBQWU7QUFDdEQsV0FBT2xGLFdBQVdlLEtBQVgsQ0FBaUIwRCxjQUFqQixDQUFnQ1MsSUFBaEMsQ0FBUDtBQUNBLEdBRkQ7QUFHQSxDIiwiZmlsZSI6Ii9wYWNrYWdlcy9yb2NrZXRjaGF0X2thdGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiTWV0ZW9yLnN0YXJ0dXAoZnVuY3Rpb24oKSB7XG5cdGNvbnN0IGVuYWJsZVF1ZXJ5ID0ge1xuXHRcdF9pZDogJ0thdGV4X0VuYWJsZWQnLFxuXHRcdHZhbHVlOiB0cnVlXG5cdH07XG5cdFJvY2tldENoYXQuc2V0dGluZ3MuYWRkKCdLYXRleF9FbmFibGVkJywgdHJ1ZSwge1xuXHRcdHR5cGU6ICdib29sZWFuJyxcblx0XHRncm91cDogJ01lc3NhZ2UnLFxuXHRcdHNlY3Rpb246ICdLYXRleCcsXG5cdFx0J3B1YmxpYyc6IHRydWUsXG5cdFx0aTE4bjogJ0thdGV4X0VuYWJsZWRfRGVzY3JpcHRpb24nXG5cdH0pO1xuXHRSb2NrZXRDaGF0LnNldHRpbmdzLmFkZCgnS2F0ZXhfUGFyZW50aGVzaXNfU3ludGF4JywgdHJ1ZSwge1xuXHRcdHR5cGU6ICdib29sZWFuJyxcblx0XHRncm91cDogJ01lc3NhZ2UnLFxuXHRcdHNlY3Rpb246ICdLYXRleCcsXG5cdFx0J3B1YmxpYyc6IHRydWUsXG5cdFx0ZW5hYmxlUXVlcnksXG5cdFx0aTE4bkRlc2NyaXB0aW9uOiAnS2F0ZXhfUGFyZW50aGVzaXNfU3ludGF4X0Rlc2NyaXB0aW9uJ1xuXHR9KTtcblx0cmV0dXJuIFJvY2tldENoYXQuc2V0dGluZ3MuYWRkKCdLYXRleF9Eb2xsYXJfU3ludGF4JywgZmFsc2UsIHtcblx0XHR0eXBlOiAnYm9vbGVhbicsXG5cdFx0Z3JvdXA6ICdNZXNzYWdlJyxcblx0XHRzZWN0aW9uOiAnS2F0ZXgnLFxuXHRcdCdwdWJsaWMnOiB0cnVlLFxuXHRcdGVuYWJsZVF1ZXJ5LFxuXHRcdGkxOG5EZXNjcmlwdGlvbjogJ0thdGV4X0RvbGxhcl9TeW50YXhfRGVzY3JpcHRpb24nXG5cdH0pO1xufSk7XG5cbi8vIC0tLVxuLy8gZ2VuZXJhdGVkIGJ5IGNvZmZlZS1zY3JpcHQgMS45LjJcbiIsIi8qXG4gKiBLYVRlWCBpcyBhIGZhc3QsIGVhc3ktdG8tdXNlIEphdmFTY3JpcHQgbGlicmFyeSBmb3IgVGVYIG1hdGggcmVuZGVyaW5nIG9uIHRoZSB3ZWIuXG4gKiBodHRwczovL2dpdGh1Yi5jb20vS2hhbi9LYVRlWFxuICovXG5pbXBvcnQgXyBmcm9tICd1bmRlcnNjb3JlJztcbmltcG9ydCBzIGZyb20gJ3VuZGVyc2NvcmUuc3RyaW5nJztcblxuaW1wb3J0IGthdGV4IGZyb20gJ2thdGV4JztcblxuY2xhc3MgQm91bmRhcnkge1xuXHRjb25zdHJ1Y3RvcigpIHt9XG5cblx0bGVuZ3RoKCkge1xuXHRcdHJldHVybiB0aGlzLmVuZCAtIHRoaXMuc3RhcnQ7XG5cdH1cblxuXHRleHRyYWN0KHN0cikge1xuXHRcdHJldHVybiBzdHIuc3Vic3RyKHRoaXMuc3RhcnQsIHRoaXMubGVuZ3RoKCkpO1xuXHR9XG5cbn1cblxuY2xhc3MgS2F0ZXgge1xuXHRjb25zdHJ1Y3RvcigpIHtcblx0XHR0aGlzLmRlbGltaXRlcnNfbWFwID0gW1xuXHRcdFx0e1xuXHRcdFx0XHRvcGVuZXI6ICdcXFxcWycsXG5cdFx0XHRcdGNsb3NlcjogJ1xcXFxdJyxcblx0XHRcdFx0ZGlzcGxheU1vZGU6IHRydWUsXG5cdFx0XHRcdGVuYWJsZWQ6ICgpID0+IHtcblx0XHRcdFx0XHRyZXR1cm4gdGhpcy5wYXJlbnRoZXNpc19zeW50YXhfZW5hYmxlZCgpO1xuXHRcdFx0XHR9XG5cdFx0XHR9LCB7XG5cdFx0XHRcdG9wZW5lcjogJ1xcXFwoJyxcblx0XHRcdFx0Y2xvc2VyOiAnXFxcXCknLFxuXHRcdFx0XHRkaXNwbGF5TW9kZTogZmFsc2UsXG5cdFx0XHRcdGVuYWJsZWQ6ICgpID0+IHtcblx0XHRcdFx0XHRyZXR1cm4gdGhpcy5wYXJlbnRoZXNpc19zeW50YXhfZW5hYmxlZCgpO1xuXHRcdFx0XHR9XG5cdFx0XHR9LCB7XG5cdFx0XHRcdG9wZW5lcjogJyQkJyxcblx0XHRcdFx0Y2xvc2VyOiAnJCQnLFxuXHRcdFx0XHRkaXNwbGF5TW9kZTogdHJ1ZSxcblx0XHRcdFx0ZW5hYmxlZDogKCkgPT4ge1xuXHRcdFx0XHRcdHJldHVybiB0aGlzLmRvbGxhcl9zeW50YXhfZW5hYmxlZCgpO1xuXHRcdFx0XHR9XG5cdFx0XHR9LCB7XG5cdFx0XHRcdG9wZW5lcjogJyQnLFxuXHRcdFx0XHRjbG9zZXI6ICckJyxcblx0XHRcdFx0ZGlzcGxheU1vZGU6IGZhbHNlLFxuXHRcdFx0XHRlbmFibGVkOiAoKSA9PiB7XG5cdFx0XHRcdFx0cmV0dXJuIHRoaXMuZG9sbGFyX3N5bnRheF9lbmFibGVkKCk7XG5cdFx0XHRcdH1cblx0XHRcdH1cblx0XHRdO1xuXHR9XG5cdC8vIFNlYXJjaGVzIGZvciB0aGUgZmlyc3Qgb3BlbmluZyBkZWxpbWl0ZXIgaW4gdGhlIHN0cmluZyBmcm9tIGEgZ2l2ZW4gcG9zaXRpb25cblxuXHRmaW5kX29wZW5pbmdfZGVsaW1pdGVyKHN0ciwgc3RhcnQpIHsgLy8gU2VhcmNoIHRoZSBzdHJpbmcgZm9yIGVhY2ggb3BlbmluZyBkZWxpbWl0ZXJcblx0XHRjb25zdCBtYXRjaGVzID0gKCgpID0+IHtcblx0XHRcdGNvbnN0IG1hcCA9IHRoaXMuZGVsaW1pdGVyc19tYXA7XG5cdFx0XHRjb25zdCByZXN1bHRzID0gW107XG5cblx0XHRcdG1hcC5mb3JFYWNoKChvcCkgPT4ge1xuXHRcdFx0XHRpZiAob3AuZW5hYmxlZCgpKSB7XG5cdFx0XHRcdFx0cmVzdWx0cy5wdXNoKHtcblx0XHRcdFx0XHRcdG9wdGlvbnM6IG9wLFxuXHRcdFx0XHRcdFx0cG9zOiBzdHIuaW5kZXhPZihvcC5vcGVuZXIsIHN0YXJ0KVxuXHRcdFx0XHRcdH0pO1xuXHRcdFx0XHR9XG5cdFx0XHR9KTtcblx0XHRcdHJldHVybiByZXN1bHRzO1xuXHRcdH0pKCk7XG5cblx0XHRjb25zdCBwb3NpdGlvbnMgPSAoKCkgPT4ge1xuXHRcdFx0Y29uc3QgcmVzdWx0cyA9IFtdO1xuXHRcdFx0bWF0Y2hlcy5mb3JFYWNoKChwb3MpID0+IHtcblx0XHRcdFx0aWYgKHBvcy5wb3MgPj0gMCkge1xuXHRcdFx0XHRcdHJlc3VsdHMucHVzaChwb3MucG9zKTtcblx0XHRcdFx0fVxuXHRcdFx0fSk7XG5cdFx0XHRyZXR1cm4gcmVzdWx0cztcblx0XHR9KSgpO1xuXG5cdFx0Ly8gTm8gb3BlbmluZyBkZWxpbWl0ZXJzIHdlcmUgZm91bmRcblx0XHRpZiAocG9zaXRpb25zLmxlbmd0aCA9PT0gMCkge1xuXHRcdFx0cmV0dXJuIG51bGw7XG5cdFx0fVxuXG5cdFx0Ly9UYWtlIHRoZSBmaXJzdCBkZWxpbWl0ZXIgZm91bmRcblx0XHRjb25zdCBwb3MgPSBNYXRoLm1pbi5hcHBseShNYXRoLCBwb3NpdGlvbnMpO1xuXG5cdFx0Y29uc3QgbWF0Y2hfaW5kZXggPSAoKCk9PiB7XG5cdFx0XHRjb25zdCByZXN1bHRzID0gW107XG5cdFx0XHRtYXRjaGVzLmZvckVhY2goKG0pID0+IHtcblx0XHRcdFx0cmVzdWx0cy5wdXNoKG0ucG9zKTtcblx0XHRcdH0pO1xuXHRcdFx0cmV0dXJuIHJlc3VsdHM7XG5cdFx0fSkoKS5pbmRleE9mKHBvcyk7XG5cblx0XHRjb25zdCBtYXRjaCA9IG1hdGNoZXNbbWF0Y2hfaW5kZXhdO1xuXHRcdHJldHVybiBtYXRjaDtcblx0fVxuXG5cdC8vIFJldHVybnMgdGhlIG91dGVyIGFuZCBpbm5lciBib3VuZGFyaWVzIG9mIHRoZSBsYXRleCBibG9jayBzdGFydGluZ1xuXHQvLyBhdCB0aGUgZ2l2ZW4gb3BlbmluZyBkZWxpbWl0ZXJcblx0Z2V0X2xhdGV4X2JvdW5kYXJpZXMoc3RyLCBvcGVuaW5nX2RlbGltaXRlcl9tYXRjaCkge1xuXHRcdGNvbnN0IGlubmVyID0gbmV3IEJvdW5kYXJ5O1xuXHRcdGNvbnN0IG91dGVyID0gbmV3IEJvdW5kYXJ5O1xuXG5cdFx0Ly8gVGhlIGNsb3NpbmcgZGVsaW1pdGVyIG1hdGNoaW5nIHRvIHRoZSBvcGVuaW5nIG9uZVxuXHRcdGNvbnN0IGNsb3NlciA9IG9wZW5pbmdfZGVsaW1pdGVyX21hdGNoLm9wdGlvbnMuY2xvc2VyO1xuXHRcdG91dGVyLnN0YXJ0ID0gb3BlbmluZ19kZWxpbWl0ZXJfbWF0Y2gucG9zO1xuXHRcdGlubmVyLnN0YXJ0ID0gb3BlbmluZ19kZWxpbWl0ZXJfbWF0Y2gucG9zICsgY2xvc2VyLmxlbmd0aDtcblxuXHRcdC8vIFNlYXJjaCBmb3IgYSBjbG9zZXIgZGVsaW1pdGVyIGFmdGVyIHRoZSBvcGVuaW5nIG9uZVxuXHRcdGNvbnN0IGNsb3Nlcl9pbmRleCA9IHN0ci5zdWJzdHIoaW5uZXIuc3RhcnQpLmluZGV4T2YoY2xvc2VyKTtcblx0XHRpZiAoY2xvc2VyX2luZGV4IDwgMCkge1xuXHRcdFx0cmV0dXJuIG51bGw7XG5cdFx0fVxuXHRcdGlubmVyLmVuZCA9IGlubmVyLnN0YXJ0ICsgY2xvc2VyX2luZGV4O1xuXHRcdG91dGVyLmVuZCA9IGlubmVyLmVuZCArIGNsb3Nlci5sZW5ndGg7XG5cdFx0cmV0dXJuIHtcblx0XHRcdG91dGVyLFxuXHRcdFx0aW5uZXJcblx0XHR9O1xuXHR9XG5cblx0Ly8gU2VhcmNoZXMgZm9yIHRoZSBmaXJzdCBsYXRleCBibG9jayBpbiB0aGUgZ2l2ZW4gc3RyaW5nXG5cdGZpbmRfbGF0ZXgoc3RyKSB7XG5cdFx0bGV0IHN0YXJ0ID0gMDtcblx0XHRsZXQgb3BlbmluZ19kZWxpbWl0ZXJfbWF0Y2g7XG5cblx0XHR3aGlsZSAoKG9wZW5pbmdfZGVsaW1pdGVyX21hdGNoID0gdGhpcy5maW5kX29wZW5pbmdfZGVsaW1pdGVyKHN0ciwgc3RhcnQrKykpICE9IG51bGwpIHtcblx0XHRcdGNvbnN0IG1hdGNoID0gdGhpcy5nZXRfbGF0ZXhfYm91bmRhcmllcyhzdHIsIG9wZW5pbmdfZGVsaW1pdGVyX21hdGNoKTtcblx0XHRcdGlmIChtYXRjaCAmJiBtYXRjaC5pbm5lci5leHRyYWN0KHN0cikudHJpbSgpLmxlbmd0aCkge1xuXHRcdFx0XHRtYXRjaC5vcHRpb25zID0gb3BlbmluZ19kZWxpbWl0ZXJfbWF0Y2gub3B0aW9ucztcblx0XHRcdFx0cmV0dXJuIG1hdGNoO1xuXHRcdFx0fVxuXHRcdH1cblx0XHRyZXR1cm4gbnVsbDtcblx0fVxuXG5cdC8vIEJyZWFrcyBhIG1lc3NhZ2UgdG8gd2hhdCBjb21lcyBiZWZvcmUsIGFmdGVyIGFuZCB0byB0aGUgY29udGVudCBvZiBhXG5cdC8vIG1hdGNoZWQgbGF0ZXggYmxvY2tcblx0ZXh0cmFjdF9sYXRleChzdHIsIG1hdGNoKSB7XG5cdFx0Y29uc3QgYmVmb3JlID0gc3RyLnN1YnN0cigwLCBtYXRjaC5vdXRlci5zdGFydCk7XG5cdFx0Y29uc3QgYWZ0ZXIgPSBzdHIuc3Vic3RyKG1hdGNoLm91dGVyLmVuZCk7XG5cdFx0bGV0IGxhdGV4ID0gbWF0Y2guaW5uZXIuZXh0cmFjdChzdHIpO1xuXHRcdGxhdGV4ID0gcy51bmVzY2FwZUhUTUwobGF0ZXgpO1xuXHRcdHJldHVybiB7XG5cdFx0XHRiZWZvcmUsXG5cdFx0XHRsYXRleCxcblx0XHRcdGFmdGVyXG5cdFx0fTtcblx0fVxuXG5cdC8vIFRha2VzIGEgbGF0ZXggbWF0aCBzdHJpbmcgYW5kIHRoZSBkZXNpcmVkIGRpc3BsYXkgbW9kZSBhbmQgcmVuZGVycyBpdFxuXHQvLyB0byBIVE1MIHVzaW5nIHRoZSBLYVRlWCBsaWJyYXJ5XG5cdHJlbmRlcl9sYXRleChsYXRleCwgZGlzcGxheU1vZGUpIHtcblx0XHRsZXQgcmVuZGVyZWQ7XG5cdFx0dHJ5IHtcblx0XHRcdHJlbmRlcmVkID0ga2F0ZXgucmVuZGVyVG9TdHJpbmcobGF0ZXgsIHtcblx0XHRcdFx0ZGlzcGxheU1vZGVcblx0XHRcdH0pO1xuXHRcdH0gY2F0Y2ggKGVycm9yKSB7XG5cdFx0XHRjb25zdCBlID0gZXJyb3I7XG5cdFx0XHRjb25zdCBkaXNwbGF5X21vZGUgPSBkaXNwbGF5TW9kZSA/ICdibG9jaycgOiAnaW5saW5lJztcblx0XHRcdHJlbmRlcmVkID0gYDxkaXYgY2xhc3M9XCJrYXRleC1lcnJvciBrYXRleC0keyBkaXNwbGF5X21vZGUgfS1lcnJvclwiPmA7XG5cdFx0XHRyZW5kZXJlZCArPSBgJHsgcy5lc2NhcGVIVE1MKGUubWVzc2FnZSkgfWA7XG5cdFx0XHRyZW5kZXJlZCArPSAnPC9kaXY+Jztcblx0XHR9XG5cdFx0cmV0dXJuIHJlbmRlcmVkO1xuXHR9XG5cblx0Ly8gVGFrZXMgYSBzdHJpbmcgYW5kIHJlbmRlcnMgYWxsIGxhdGV4IGJsb2NrcyBpbnNpZGUgaXRcblx0cmVuZGVyKHN0ciwgcmVuZGVyX2Z1bmMpIHtcblx0XHRsZXQgcmVzdWx0ID0gJyc7XG5cdFx0d2hpbGUgKHRoaXMuZmluZF9sYXRleChzdHIpICE9IG51bGwpIHtcblx0XHRcdC8vIEZpbmQgdGhlIGZpcnN0IGxhdGV4IGJsb2NrIGluIHRoZSBzdHJpbmdcblx0XHRcdGNvbnN0IG1hdGNoID0gdGhpcy5maW5kX2xhdGV4KHN0cik7XG5cdFx0XHRjb25zdCBwYXJ0cyA9IHRoaXMuZXh0cmFjdF9sYXRleChzdHIsIG1hdGNoKTtcblxuXHRcdFx0Ly8gQWRkIHRvIHRoZSByZXVzbHQgd2hhdCBjb21lcyBiZWZvcmUgdGhlIGxhdGV4IGJsb2NrIGFzIHdlbGwgYXNcblx0XHRcdC8vIHRoZSByZW5kZXJlZCBsYXRleCBjb250ZW50XG5cdFx0XHRjb25zdCByZW5kZXJlZCA9IHJlbmRlcl9mdW5jKHBhcnRzLmxhdGV4LCBtYXRjaC5vcHRpb25zLmRpc3BsYXlNb2RlKTtcblx0XHRcdHJlc3VsdCArPSBwYXJ0cy5iZWZvcmUgKyByZW5kZXJlZDtcblx0XHRcdC8vIFNldCB3aGF0IGNvbWVzIGFmdGVyIHRoZSBsYXRleCBibG9jayB0byBiZSBleGFtaW5lZCBuZXh0XG5cdFx0XHRzdHIgPSBwYXJ0cy5hZnRlcjtcblx0XHR9XG5cdFx0cmV0dXJuIHJlc3VsdCArPSBzdHI7XG5cdH1cblxuXHQvLyBUYWtlcyBhIHJvY2tldGNoYXQgbWVzc2FnZSBhbmQgcmVuZGVycyBsYXRleCBpbiBpdHMgY29udGVudFxuXHRyZW5kZXJfbWVzc2FnZShtZXNzYWdlKSB7XG5cdFx0Ly9SZW5kZXIgb25seSBpZiBlbmFibGVkIGluIGFkbWluIHBhbmVsXG5cdFx0bGV0IHJlbmRlcl9mdW5jO1xuXHRcdGlmICh0aGlzLmthdGV4X2VuYWJsZWQoKSkge1xuXHRcdFx0bGV0IG1zZyA9IG1lc3NhZ2U7XG5cdFx0XHRpZiAoIV8uaXNTdHJpbmcobWVzc2FnZSkpIHtcblx0XHRcdFx0aWYgKHMudHJpbShtZXNzYWdlLmh0bWwpKSB7XG5cdFx0XHRcdFx0bXNnID0gbWVzc2FnZS5odG1sO1xuXHRcdFx0XHR9IGVsc2Uge1xuXHRcdFx0XHRcdHJldHVybiBtZXNzYWdlO1xuXHRcdFx0XHR9XG5cdFx0XHR9XG5cdFx0XHRpZiAoXy5pc1N0cmluZyhtZXNzYWdlKSkge1xuXHRcdFx0XHRyZW5kZXJfZnVuYyA9IChsYXRleCwgZGlzcGxheU1vZGUpID0+IHtcblx0XHRcdFx0XHRyZXR1cm4gdGhpcy5yZW5kZXJfbGF0ZXgobGF0ZXgsIGRpc3BsYXlNb2RlKTtcblx0XHRcdFx0fTtcblx0XHRcdH0gZWxzZSB7XG5cdFx0XHRcdGlmIChtZXNzYWdlLnRva2VucyA9PSBudWxsKSB7XG5cdFx0XHRcdFx0bWVzc2FnZS50b2tlbnMgPSBbXTtcblx0XHRcdFx0fVxuXHRcdFx0XHRyZW5kZXJfZnVuYyA9IChsYXRleCwgZGlzcGxheU1vZGUpID0+IHtcblx0XHRcdFx0XHRjb25zdCB0b2tlbiA9IGA9IT0keyBSYW5kb20uaWQoKSB9PSE9YDtcblx0XHRcdFx0XHRtZXNzYWdlLnRva2Vucy5wdXNoKHtcblx0XHRcdFx0XHRcdHRva2VuLFxuXHRcdFx0XHRcdFx0dGV4dDogdGhpcy5yZW5kZXJfbGF0ZXgobGF0ZXgsIGRpc3BsYXlNb2RlKVxuXHRcdFx0XHRcdH0pO1xuXHRcdFx0XHRcdHJldHVybiB0b2tlbjtcblx0XHRcdFx0fTtcblx0XHRcdH1cblx0XHRcdG1zZyA9IHRoaXMucmVuZGVyKG1zZywgcmVuZGVyX2Z1bmMpO1xuXHRcdFx0aWYgKCFfLmlzU3RyaW5nKG1lc3NhZ2UpKSB7XG5cdFx0XHRcdG1lc3NhZ2UuaHRtbCA9IG1zZztcblx0XHRcdH0gZWxzZSB7XG5cdFx0XHRcdG1lc3NhZ2UgPSBtc2c7XG5cdFx0XHR9XG5cdFx0fVxuXHRcdHJldHVybiBtZXNzYWdlO1xuXHR9XG5cblx0a2F0ZXhfZW5hYmxlZCgpIHtcblx0XHRyZXR1cm4gUm9ja2V0Q2hhdC5zZXR0aW5ncy5nZXQoJ0thdGV4X0VuYWJsZWQnKTtcblx0fVxuXG5cdGRvbGxhcl9zeW50YXhfZW5hYmxlZCgpIHtcblx0XHRyZXR1cm4gUm9ja2V0Q2hhdC5zZXR0aW5ncy5nZXQoJ0thdGV4X0RvbGxhcl9TeW50YXgnKTtcblx0fVxuXG5cdHBhcmVudGhlc2lzX3N5bnRheF9lbmFibGVkKCkge1xuXHRcdHJldHVybiBSb2NrZXRDaGF0LnNldHRpbmdzLmdldCgnS2F0ZXhfUGFyZW50aGVzaXNfU3ludGF4Jyk7XG5cdH1cblxufVxuXG5Sb2NrZXRDaGF0LmthdGV4ID0gbmV3IEthdGV4O1xuXG5jb25zdCBjYiA9IFJvY2tldENoYXQua2F0ZXgucmVuZGVyX21lc3NhZ2UuYmluZChSb2NrZXRDaGF0LmthdGV4KTtcblxuUm9ja2V0Q2hhdC5jYWxsYmFja3MuYWRkKCdyZW5kZXJNZXNzYWdlJywgY2IsIFJvY2tldENoYXQuY2FsbGJhY2tzLnByaW9yaXR5LkhJR0ggLSAxLCAna2F0ZXgnKTtcblxuaWYgKE1ldGVvci5pc0NsaWVudCkge1xuXHRCbGF6ZS5yZWdpc3RlckhlbHBlcignUm9ja2V0Q2hhdEthdGV4JywgZnVuY3Rpb24odGV4dCkge1xuXHRcdHJldHVybiBSb2NrZXRDaGF0LmthdGV4LnJlbmRlcl9tZXNzYWdlKHRleHQpO1xuXHR9KTtcbn1cbiJdfQ==
